---
  - name: Set Router config
    template:
      src: frr.conf.j2
      dest: /etc/frr/frr.conf
      owner: root
      group: root
      mode: 0644

  - name: Restart frr service
    systemd:
      state: restarted
      name: frr
